[default.general]
chip = "nrf52833_xxAA"  # for micro:bit v2
#chip = "nrf51822_xxAA"  # for micro:bit v1

[default.reset]
halt_afterwards = true

[default.rtt]
enabled = false

[default.gdb]
enabled = true
